version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - DATABASE_URL=sqlite:///devops.db
    volumes:
      - ./instance:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/system-info"]
      interval: 30s
      timeout: 10s
      retries: 3
